use_frameworks!

def available_pods
    pod 'AwesomePurchase', :path => '../'
end

# Pod for different targets
target 'AwesomePurchase_Example' do
    available_pods
end

target 'AwesomePurchase_Tests' do
    available_pods
end
